basepath = "../"

locales = [
    "ja"
]

[[paths]]
    reference = "templates/summit/messages/bigscreen-debos-image-rpi4/*.pot"
    l10n = "{locale}/summit/messages/bigscreen-debos-image-rpi4/*.po"

