basepath = "../"

locales = [
    "ja"
]

[[paths]]
    reference = "templates/summit/messages/documentation-docs-krita-org/*.pot"
    l10n = "{locale}/summit/messages/documentation-docs-krita-org/*.po"

