basepath = "../"

locales = [
    "ja"
]

[[paths]]
    reference = "templates/summit/messages/drkonqi-pk-debug-installer/*.pot"
    l10n = "{locale}/summit/messages/drkonqi-pk-debug-installer/*.po"

