basepath = "../"

locales = [
    "ja"
]

[[paths]]
    reference = "templates/summit/messages/kdesdk-devenv-dependencies/*.pot"
    l10n = "{locale}/summit/messages/kdesdk-devenv-dependencies/*.po"

