basepath = "../"

locales = [
    "ja"
]

[[paths]]
    reference = "templates/summit/messages/plasma-workspace-wallpapers/*.pot"
    l10n = "{locale}/summit/messages/plasma-workspace-wallpapers/*.po"

