basepath = "../"

locales = [
    "ja"
]

[[paths]]
    reference = "templates/summit/messages/plasma-browser-integration/*.pot"
    l10n = "{locale}/summit/messages/plasma-browser-integration/*.po"

