basepath = "../"

locales = [
    "ja"
]

[[paths]]
    reference = "templates/summit/messages/websites-manifesto-kde-org/*.pot"
    l10n = "{locale}/summit/messages/websites-manifesto-kde-org/*.po"

