basepath = "../"

locales = [
    "ja"
]

[[paths]]
    reference = "templates/summit/messages/websites-wiki-rolisteam-org/*.pot"
    l10n = "{locale}/summit/messages/websites-wiki-rolisteam-org/*.po"

