basepath = "../"

locales = [
    "ja"
]

[[paths]]
    reference = "templates/summit/messages/wikidata-voice-application/*.pot"
    l10n = "{locale}/summit/messages/wikidata-voice-application/*.po"

