name: Sync Pontoon

on:
  workflow_dispatch:

jobs:
  sync-pontoon:
    runs-on: ubuntu-latest
    environment: Sync
    env:
       DATABASE_URL: ${{ secrets.DATABASE_URL }}
       SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: 'mozilla/pontoon'
      - uses: actions/checkout@v6
        with:
          path: 'media/translations'
      - name: Link repository
        run: |-
          ./media/translations/link_repo.sh
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
      - name: Install libs
        run: sudo apt-get update && sudo apt-get install libpq-dev libxml2-dev libxslt-dev -y
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt
      - name: Setup Git Credential
        run: |-
          git config --global credential.helper store
          echo "${{ secrets.GIT_CREDENTIAL }}" > ~/.git-credentials
      - name: Run Python
        run: python manage.py sync_projects
